### ISSUE TITLE
Bilder des Monats BOT

### ISSUE THREAD

**Issue by pulponair** [draussenfunker/draussenfunker.github.io#17]
## Story
As a community we want the pictures of the month article being created automatically by counting emoticon reactions an certain tag at by beginning of the following month.
As a community we are aware of the fact that this story hast to be specified more precisely 

## Requierments
Missing atm

**Comment by IamBuildDifferent** [comment]
Is this request now unneccesary, because I programmed one?
https://github.com/IamBuildDifferent/Draussenfunker-BilderDesMonats-Bot

**Comment by zeidlos** [comment]
@IamBuildDifferent yes, you fixed this issue. :D 

Where's that code by the way?

**Comment by IamBuildDifferent** [comment]
here: https://github.com/IamBuildDifferent/Draussenfunker-BilderDesMonats-Bot
